# To run: conda env create -f environment.yml
name: nerf
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - matplotlib
  - imageio
  - imageio-ffmpeg
  - configargparse
  - imagemagick
  - pip:
      - tensorflow[and-cuda]
